# format = "$all$git$character"
format = "$all$custom$character"
add_newline = false

[aws]
symbol = "  "
disabled = true

[[battery.display]]
threshold = 25

[cmd_duration]
show_milliseconds = true
format = " [$duration](fg:12 dimmed bold) "

[conda]
symbol = " "
format = ' [$symbol$environment]($style) '

[dart]
symbol = " "

[directory]
read_only = " "
style = "cyan"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = " [$symbol($version )]($style)"

[elm]
symbol = " "

[git_branch]
symbol = " "
format = " [$symbol$branch](purple) "

[git_status]
style = "purple"
format = '([$all_status$ahead_behind]($style) )'
conflicted = " "
ahead = " "
behind = " "
diverged = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[$hostname](8)  "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "
format = " [$symbol($version )]($style)"

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nodejs]
format = " [$symbol($version )](green)"

[nix_shell]
symbol = " "

[package]
symbol = " "
format = " [$symbol($version )]($style)"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )( $virtualenv )](yellow)'

[ruby]
symbol = " "
format = " [$symbol($version )](red)"

[rust]
symbol = " "
format = " [$symbol($version )](red)"

[scala]
symbol = " "

[shlvl]
disabled = false
threshold = 3
symbol = " "

[swift]
symbol = "ﯣ "

[username]
format = "[$user@](8)"

[custom.arch]
description = "The current architecture"
symbol = "礪"
format = "[$symbol](cyan)[intel ](bold red)"
when = """ test "$(arch)" = "i386" """
