add_newline = false

[aws]
symbol = "  "
disabled = true

[cmd_duration]
show_milliseconds = true
format = " [$duration](fg:12 dimmed bold) "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
style = "cyan"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = " [$symbol$branch](purple) "

[git_status]
style = "purple"
format = '([$all_status$ahead_behind]($style) )'
conflicted = " "
ahead = " "
behind = " "
diverged = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "
format = " [$symbol($version )]($style)"

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nodejs]
format = " [$symbol($version )](green)"

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](yellow)'

[ruby]
symbol = " "
format = " [$symbol($version )](red)"

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
disabled = false
threshold = 3

[swift]
symbol = "ﯣ "
